[package]
name = "dll_main_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.winapi]
version = "*"
features = ["minwindef", "winnt", "libloaderapi", "processthreadsapi", "handleapi"]